### ISSUE TITLE
Environment Option doesn't seem to have any affect in Measurement Templates.

### ISSUE THREAD

**Issue by JustinB555** [ironmonk108/enhanced-terrain-layer#24]
I was messing around with the available options to see how I can use them. I noticed that you said that the modifiers can be set to spells, so I tested it using Spike Growth (the one that comes with the DnD5e system). It was there, but I didn't see any noticeable difference when I gave it an environment. I attached a pic of what I am looking at, these are the settings I had for the template. The only thing I have not messed with is changing the template's texture, but I wanted to see what your thoughts were on the issue.
![Environment issue](https://user-images.githubusercontent.com/60529781/118345181-db5f1080-b500-11eb-812f-5b881bb1b0b9.PNG)

**Comment by ironmonk88** [comment]
Not an issue.
Environment just stores some information about that terrain, there's no visual cues.  What you need is a ruler that will use that information.
Currently the only one I know of is for Pathfinder.  But I think someone is working on one for DnD5e.

It's meant for classes that ignore difficult terrain caused by something.  Like Ranger and their favored terrain.  But unless the ruler knows how to apply that information, it's really just for the GM to reference.

At some point I have plans to show a little icon with information, same way I do with terrain, but for right now I'm waiting until 0.8.x is released because there are changes to how measured templates are displayed.

**Comment by JustinB555** [comment]
Thanks for clearing that up. An added icon would help keep track of what environment is in effect, so I hope to see that sometime in the future. Thanks for your hard work with this, I really hope to put it to good use.
