### ISSUE TITLE
[Bug?] Hidden terrain is not calculated

### ISSUE THREAD

**Issue by miguel-pinto-prodmad** [ironmonk108/enhanced-terrain-layer#27]
Not sure if it's an error to report here on on other modules but, when a terrain polygon is visible, if a token is dragged over it, the rule shows the correct multiplies values (based on the difficult terrain).

However, if the terrain is hidden, the ruler doesn't take it into account and doesn't apply the multiplier.

I want to be able to add difficult terrain but not show it to the players because the map already has a nice representation of the difficult terrains and it would be a shame for the players to have to see a bland dashed area instead of the cool map.

Maybe the difficult terrain could have a separate visible/invisible option that only control the visibility to players and another separate enabled/disabled option that controls if the terrain should or not be considered in the movement/ruler calculation?

Thanks.

**Comment by ironmonk88** [comment]
Hidden terrain is meant to be so you can conditionally deactivate terrain.  Such as a landslide that hasn't happened yet, or a rubble pile that gets cleared.  It won't be calculated because it's not an active terrain any more.

You can hide the terrain from the players by going into the settings and turning off "Show on drag".
![image](https://user-images.githubusercontent.com/75920956/119093688-dc8eb280-b9c4-11eb-801a-b17f28e6c035.png)

Make sure the "Terrain always visible" toggle is turned off. 
![image](https://user-images.githubusercontent.com/75920956/119093608-c41e9800-b9c4-11eb-8458-ad68ac678d43.png)
And the players won't see the terrain, but it will still be active.
