### ISSUE TITLE
Allowing query individual pixel terrain cost in gridded mode

### ISSUE THREAD

**Issue by Teshynil** [ironmonk108/enhanced-terrain-layer#40]
As in the title, allowing a method to query the individual pixel cost while a grid is enabled.

**Comment by ironmonk88** [comment]
you mean... `canvas.terrain.terrainFromPixel(x,y)`?

**Comment by manuelVo** [comment]
The reason for this issue is that currently Terrain Ruler doesn't support the euclidean Measurement rule of DnD5e. That measurement rule is supposed to measure the same distances that gridless would measure, while still snapping to a square grid. If Terrain Ruler is to support this, it needs to fetch the terrain cost of a specific pixel (like it does in gridless) from Enhanced Terrain Layer while a gridded scene is active.

I see 3 ways how this could be tackled:
- ETL could leave it's API as is and monitor the diagonalRule flag. If it's set to Euclidean it could switch to gridless mode internally.
- ETL could expose a new API endpoint that always accesses terrain data on a pixel level, independently of which grid type is active on the scene.
- ETL could add an option to it's cost function that force the cost-function to ignore the grid and read pixel-based terrain data instead.

**Comment by ironmonk88** [comment]
Okay, I think I'm following now.
So essentially you'd like an option to use the cost function as gridless even if there's a grid.

**Comment by manuelVo** [comment]
Am I right to assume that this has been implemented in https://github.com/ironmonk88/enhanced-terrain-layer/commit/04e1e4e6b3af3032a3d61e8755f24c02ec7c842f?

**Comment by ironmonk88** [comment]
This has been implemented.
Closing the ticket.
