### ISSUE TITLE
What do obstacles do?

### ISSUE THREAD

**Issue by Weissrolf** [ironmonk108/enhanced-terrain-layer#75]
Hello. Great module, like many of yours! :)

What does the "Obstacles" option do exactly? I assume it would enable Terrain Ruler to do some calculations with it, but currently it seems more like a placeholder/notes thing?

**Comment by ironmonk88** [comment]
Obstacles lets you set both the environment and object on terrain.  With it turned off, the lists are joined, but with it turned on you can have things like Arctic Rubble.  So if you have a ruler that makes the distinction and you have a character that ignores difficult terrain caused by Arctic, or by Rubble it can ignore that terrain.
